CREATE TABLE BINARIES (
  BIN_ID       BIGINT             AUTO_INCREMENT NOT NULL PRIMARY KEY,
  APP_NAME     VARCHAR(255)       NOT NULL,
  UPLOAD_TIME  TIMESTAMP          NOT NULL,
  BINARY_TYPE  VARCHAR(10)        NOT NULL,
  BINARY       BYTEA              NOT NULL
);

CREATE TABLE JOBS (
  JOB_ID          VARCHAR(255)    NOT NULL PRIMARY KEY,
  CONTEXT_NAME    VARCHAR(255)    NOT NULL,
  BIN_ID          INTEGER         NOT NULL,
  CLASSPATH       VARCHAR(255)    NOT NULL,
  START_TIME      TIMESTAMP,
  END_TIME        TIMESTAMP,
  STATUS          VARCHAR(255)    NOT NULL,
  ERROR           CLOB
);

CREATE TABLE CONFIGS (
  CFG_ID       BIGINT             AUTO_INCREMENT NOT NULL PRIMARY KEY,
  JOB_ID      VARCHAR(255)        NOT NULL,
  JOB_CONFIG     CLOB             NOT NULL
);
